services:
  node-red:
    env_file:
      - .env
    build: .
    image: booq-node-red:latest
    ports:
      - "1880:1880"
    environment:
      TZ: Europe/Warsaw
    volumes:
      - node-red-data:/data
      - ./scripts:/data/scripts
      - ./config:/data/config
    restart: unless-stopped

volumes:
  node-red-data:
