apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: node-red
  labels:
    app.kubernetes.io/name: node-red
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>
# Aby wygenerować wartość .dockerconfigjson, wykonaj:
#
#   kubectl create secret docker-registry ghcr-secret \
#     --namespace node-red \
#     --docker-server=ghcr.io \
#     --docker-username=<github-username> \
#     --docker-password=<PAT> \
#     --dry-run=client -o yaml
#
# i skopiuj wygenerowaną wartość .dockerconfigjson powyżej.
